# Generated by Django 2.1.7 on 2019-02-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsrouter', '0003_load_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='channel_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the channels you want to filter for (or leave it blank to not filter any).', related_name='channel_filters', to='eventsrouter.Channel'),
        ),
        migrations.AlterField(
            model_name='route',
            name='event_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the events you want to filter for (or leave it blank to not filter any).', related_name='event_filters', to='eventsrouter.Event'),
        ),
    ]
