# Generated by Django 2.2 on 2019-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsrouter', '0004_auto_20190228_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='channel_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the channels you want to filter for (or leave it blank to not filter any).', to='eventsrouter.Channel'),
        ),
        migrations.AlterField(
            model_name='route',
            name='event_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the events you want to filter for (or leave it blank to not filter any).', to='eventsrouter.Event'),
        ),
    ]
