# Generated by Django 2.2.1 on 2019-05-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsrouter', '0004_auto_20190228_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='verified',
        ),
        migrations.AlterField(
            model_name='route',
            name='channel_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the channels you want to filter for (or leave it blank to not filter any).', to='eventsrouter.Channel'),
        ),
        migrations.AlterField(
            model_name='route',
            name='endpoint',
            field=models.URLField(help_text="URL to another app's API", unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='event_filters',
            field=models.ManyToManyField(blank=True, help_text='Choose the events you want to filter for (or leave it blank to not filter any).', to='eventsrouter.Event'),
        ),
    ]
