# Generated by Django 2.2 on 2019-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsrouter', '0005_auto_20190411_1115'),
        ('eventsrouter', '0005_auto_20190523_1557'),
    ]

    operations = [
    ]
